### ISSUE TITLE
Hey bug

### ISSUE THREAD

**Issue by Tuvqlu** [hachkingtohach1/EndSkyWars#1]
![65A814B6-894C-4FEB-98C5-56ED6016A917](https://user-images.githubusercontent.com/98550458/169032996-3cc18027-fb23-4b0f-a722-c7ac6e0723f6.jpeg)

super excited for this plugin! Mind  fixing this bug, and telling me more about the cosmetics and level system?

**Comment by DavidGlitch04** [comment]
You need an SQL because the plugin uses it

**Comment by Tuvqlu** [comment]
Oh please let this work this looks way to cool! COSMETICS LEVELS RANKINGS BEST SW EVER!




It’s weird I’m so excited and so nervous

**Comment by DavidGlitch04** [comment]
Create SQL with xampp in [here](https://www.youtube.com/watch?v=9qt2dv477Y0)
