### ISSUE TITLE
MySQLs crash

### ISSUE THREAD

**Issue by Tuvqlu** [hachkingtohach1/EndSkyWars#2]
Help @
![2448390F-40D8-43ED-85FD-EAB2A27CC9A6](https://user-images.githubusercontent.com/98550458/169071682-b721232a-aee1-4aae-a1e8-a0ca2921802e.jpeg)

**Comment by hachkingtohach1** [comment]
You need to make sure that your MySql works or that you can reset your SQL so that it runs.

**Comment by hachkingtohach1** [comment]
Ok now you need create new database with name is "skywars"

**Comment by hachkingtohach1** [comment]
Tomorrow I will make a specific video to create and set up for this plugin thank you for using it!

**Comment by Tuvqlu** [comment]
Im very excited! Thank you so much for this plugin! I have a little feature idea, and it’s big. Make it so you can buy cosmetics with level or something. Like once ur a certain level you get cosmetic. As well, it says your level next to name in chat. And when you setup arena it automatically backs map up. Thankyou!

**Comment by hachkingtohach1** [comment]
ok thanks your idea
