### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by IpodCraft** [hachkingtohach1/EndSkyWars#3]
Error: Call to undefined method jojoe77777\FormAPI\FormAPI::createSimpleForm()
File: plugins/EndSkyWars_dev-20.phar/src/hachkingtohach1/SkyWars/form/SoloModeForm
Line: 40
Type: Error

**Comment by IpodCraft** [comment]
When you enter the waiting lobby, the countdown to start is frozen at 14s and does not tp you to the world of skywars

**Comment by TheBrayanYt4056O** [comment]
> When you enter the waiting lobby, the countdown to start is frozen at 14s and does not tp you to the world of skywars
Hey bro pass me the MySQL please

**Comment by IpodCraft** [comment]
> same thing: Call to undefined method jojoe77777\FormAPI\FormAPI::createSimpleForm()" (EXCEPTION) in "plugins/EndSkyWars_dev-16.phar/src/hachkingtohach1/SkyWars/form/RankedModeFor

I already solved this problem and it's because I don't have the original FormAPI from Jojoe77777.
Here is the link to download it: https://poggit.pmmp.io/r/150202/FormAPI.phar

**Comment by Tuvqlu** [comment]
Also triple npc does not place

**Comment by hachkingtohach1** [comment]
https://github.com/hachkingtohach1/EndSkyWars/blob/master/README.md
