### ISSUE TITLE
Triple NPC

### ISSUE THREAD

**Issue by Missouriii** [hachkingtohach1/EndSkyWars#4]
triple npc does not place

also every form crashes:

Call to undefined method jojoe77777\FormAPI\FormAPI::createSimpleForm()" (EXCEPTION) in "plugins/EndSkyWars_dev-16.phar/src/hachkingtohach1/SkyWars/form/RankedModeFor

also how do i get scoreboard in sw hub and it saying level next to your name ty

**Comment by Tuvqlu** [comment]
Hello I have fixed form api. Also can you make cosmetics default perms? Ty

**Comment by hachkingtohach1** [comment]
Sorry for this inconvenience, the original triple mode I came up with but for acting as a hypixel I left it but haven't deleted it yet

**Comment by Tuvqlu** [comment]
Will it be added back or no?
